# Generated by Django 4.1.7 on 2023-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbilityType',
            new_name='Ability',
        ),
        migrations.RenameModel(
            old_name='RelationshipType',
            new_name='Relationship',
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'abilities'},
        ),
        migrations.AddField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(to='heroes.ability'),
        ),
    ]
